require("dotenv").config();

// ---------------------------------------------------------------------------
// 1. PAIRS — your active watchlist (OANDA instrument format: BASE_QUOTE)
// ---------------------------------------------------------------------------
const FOREX_PAIRS = [
  "GBP_USD",
  "AUD_USD",
  "NZD_USD",
  "USD_JPY",
  "USD_CAD",
  "XAU_USD", // gold — kept for price tracking, EXCLUDED from currency strength math (not a currency)
  "GBP_JPY",
  "AUD_JPY",
  "CHF_JPY",
  "CAD_JPY",
  "NZD_JPY",
  "EUR_GBP",
  "AUD_CAD",
  "AUD_CHF",
  "AUD_NZD",
  "CAD_CHF",
  "EUR_AUD",
  "EUR_CAD",
  "EUR_CHF",
  "EUR_NZD",
  "GBP_AUD",
  "GBP_CAD",
  "GBP_CHF",
  "GBP_NZD",
  "NZD_CAD",
];

// Pairs actually usable for currency-strength math (drop metals/commodities)
const STRENGTH_PAIRS = FOREX_PAIRS.filter((p) => !p.includes("XAU"));

// Derive the unique list of real currencies present in the basket
const CURRENCIES = [
  ...new Set(STRENGTH_PAIRS.flatMap((p) => p.split("_"))),
].sort();
// -> ["AUD","CAD","CHF","EUR","GBP","JPY","NZD","USD"]

// ---------------------------------------------------------------------------
// 2. FRED SERIES IDS — short-term policy/interbank rate proxy per currency
// ---------------------------------------------------------------------------
// NOTE: FRED occasionally renames or discontinues series (e.g. the old
// US IRSTCI01 series was discontinued in 2022 — FEDFUNDS replaces it).
// Verify these resolve before relying on them long-term:
// https://fred.stlouisfed.org/series/<ID>
const FRED_POLICY_RATE_SERIES = {
  USD: "FEDFUNDS", // Effective Federal Funds Rate
  EUR: "ECBDFR", // ECB Deposit Facility Rate (the rate the ECB itself steers policy with)
  GBP: "IRSTCI01GBM156N", // UK immediate/interbank rate (OECD via FRED)
  AUD: "IRSTCI01AUM156N",
  NZD: "IRSTCI01NZM156N",
  CHF: "IRSTCI01CHM156N",
  JPY: "IRSTCI01JPM156N",
  CAD: "IRSTCI01CAM156N", // verify on FRED — follows the same OECD naming pattern as above
};

// Optional secondary layer: 10Y govt bond yield, used as a slower-moving
// "rate expectations" proxy. Differentials here matter more than levels.
const FRED_LONG_YIELD_SERIES = {
  USD: "IRLTLT01USM156N",
  EUR: "IRLTLT01EZM156N",
  GBP: "IRLTLT01GBM156N",
  JPY: "IRLTLT01JPM156N",
  CHF: "IRLTLT01CHM156N",
  AUD: "IRLTLT01AUM156N",
  NZD: "IRLTLT01NZM156N",
  CAD: "IRLTLT01CAM156N",
};

// ---------------------------------------------------------------------------
// 3. NEWS SOURCES — free RSS, no scraping of paywalled/ToS-restricted sites
// ---------------------------------------------------------------------------
const NEWS_FEEDS = [
  // General market/forex news — mentions multiple currencies, good for
  // broad sentiment sweeps
  {
    name: "Investing.com Forex News",
    url: "https://www.investing.com/rss/news_1.rss",
  },
  { name: "FXStreet News", url: "https://www.fxstreet.com/rss/news" },
  {
    name: "CNBC Economy",
    url: "https://www.cnbc.com/id/20910258/device/rss/rss.html",
  },
  {
    name: "CNBC World Markets",
    url: "https://www.cnbc.com/id/100727362/device/rss/rss.html",
  },
  {
    name: "MarketWatch Top Stories",
    url: "https://feeds.content.dowjones.io/public/rss/mw_topstories",
  },

  // Central bank press releases — high-signal, low-noise, free RSS
  {
    name: "ECB Press Releases",
    url: "https://www.ecb.europa.eu/rss/press.html",
  },
  { name: "BoE News", url: "https://www.bankofengland.co.uk/rss/news" },
  {
    name: "RBA Media Releases",
    url: "https://www.rba.gov.au/rss/rss-cb-media-releases.xml",
  },
  {
    // Fed's dedicated Monetary Policy feed — narrower than "all press
    // releases", so less noise from bank-supervision/enforcement items
    // that have nothing to do with FX.
    name: "Federal Reserve Monetary Policy",
    url: "https://www.federalreserve.gov/feeds/press_monetary.xml",
  },
  {
    name: "Federal Reserve Speeches & Testimony",
    url: "https://www.federalreserve.gov/feeds/speeches_and_testimony.xml",
  },
  {
    name: "Swiss National Bank News",
    url: "https://www.snb.ch/public/en/rss/news",
  },
  {
    name: "Bank of Canada Press Releases",
    url: "https://www.bankofcanada.ca/content_type/press-releases/feed/",
  },

  // Verify before enabling — I found these central banks do publish RSS,
  // but couldn't confirm the exact current XML endpoint from search alone:
  // { name: "Bank of Japan", url: "https://www.boj.or.jp/rss/whatsnew.rdf" },      // check boj.or.jp/rss.htm for current path
  // { name: "RBNZ",          url: "TBD" },                                          // check rbnz.govt.nz for an RSS link
];

const CURRENCY_KEYWORDS = {
  USD: [
    "federal reserve",
    "fed ",
    "fomc",
    "u.s. dollar",
    "usd",
    "powell",
    "treasury secretary",
    "us treasury",
    "non-farm payrolls",
    "nonfarm payrolls",
    "dollar index",
    "dxy",
    "janet yellen",
    "bessent",
    "white house economic",
    "us inflation",
    "us cpi",
    "us gdp",
    "greenback",
    "jerome powell",
    "philip jefferson",
    "michelle bowman",
    "christopher waller",
    "lisa cook",
    "stephen miran",
    "fed rate decision",
    "fed rate cut",
    "fed rate hike",
    "us jobs report",
    "initial jobless claims",
    "us retail sales",
    "us pce",
    "core pce",
    "beige book",
    "s&p 500",
    "dow jones",
    "nasdaq",
    "treasury yields",
    "10-year treasury",
    "us debt ceiling",
    "washington economic",
    // additions
    "jpmorgan",
    "goldman sachs",
    "morgan stanley",
    "citigroup",
    "bank of america",
    "wells fargo",
    "wall street",
    "atlanta fed",
    "new york fed",
    "philadelphia fed",
    "ism manufacturing",
    "ism services",
    "consumer confidence",
    "university of michigan",
    "philly fed",
    "fed minutes",
    "dot plot",
    "fedwatch",
    "cme fedwatch",
  ],

  EUR: [
    "ecb",
    "european central bank",
    "eurozone",
    "euro area",
    "lagarde",
    "eur",
    "eurogroup",
    "european commission",
    "eu inflation",
    "eu gdp",
    "german bund",
    "bundesbank",
    "de guindos",
    "schnabel",
    "single currency",
    "euro zone",
    "brussels economic",
    "christine lagarde",
    "philip lane",
    "piero cipollone",
    "isabel schnabel",
    "german ifo",
    "zew survey",
    "german pmi",
    "french pmi",
    "italian bonds",
    "btp spread",
    "dax",
    "cac 40",
    "eurostat",
    "ez inflation",
    "ez cpi",
    "frankfurt economic",
    "ecb rate decision",
    "ecb rate cut",
    "ecb rate hike",
    "eu fiscal",
    "eu debt crisis",
    // additions
    "deutsche bank",
    "commerzbank",
    "unicredit",
    "intesa sanpaolo",
    "societe generale",
    "bnp paribas",
    "credit suisse",
    "euro stoxx",
    "german zew",
    "ifo institute",
    "european commission forecast",
  ],

  GBP: [
    "bank of england",
    "boe",
    "sterling",
    "pound",
    "gbp",
    "bailey",
    "gilt",
    "gilts",
    "uk inflation",
    "uk cpi",
    "uk gdp",
    "chancellor",
    "office for national statistics",
    "ons data",
    "mpc vote",
    "monetary policy committee",
    "downing street economic",
    "cable rate",
    "andrew bailey",
    "clare lombardelli",
    "huw pill",
    "rachel reeves",
    "uk budget",
    "uk retail sales",
    "uk employment",
    "uk wage growth",
    "ftse 100",
    "uk gilt yields",
    "boe rate decision",
    "boe rate cut",
    "boe rate hike",
    "uk pmi",
    "london economic",
    // additions
    "barclays",
    "hsbc",
    "lloyds",
    "natwest",
    "rbs",
    "british chambers of commerce",
    "cbi business confidence",
    "gfk consumer confidence",
    "rightmove house prices",
  ],

  JPY: [
    "bank of japan",
    "boj",
    "yen",
    "jpy",
    "ueda",
    "japan inflation",
    "japan cpi",
    "japan gdp",
    "tokyo cpi",
    "yield curve control",
    "jgb",
    "japanese government bond",
    "ministry of finance japan",
    "kanda",
    "tankan",
    "boj policy meeting",
    "kazuo ueda",
    "shinichi uchida",
    "ryozo himino",
    "boj rate decision",
    "boj rate hike",
    "negative interest rate japan",
    "nikkei 225",
    "japan trade balance",
    "japan wage negotiations",
    "shunto",
    "yen intervention",
    "weak yen",
    "japan gdp growth",
    "tokyo economic",
    // additions
    "mizuho",
    "mitsubishi ufj",
    "sumitomo mitsui",
    "japan post bank",
    "nomura",
    "japan machine orders",
    "japan industrial production",
    "boj governor",
  ],

  CHF: [
    "swiss national bank",
    "snb",
    "franc",
    "chf",
    "switzerland inflation",
    "swiss inflation",
    "jordan snb",
    "schlegel",
    "safe haven franc",
    "swiss gdp",
    "martin schlegel",
    "antoine martin",
    "snb rate decision",
    "snb rate cut",
    "swiss franc strength",
    "zurich economic",
    "swiss market index",
    "smi index",
    "swiss exports",
    // additions
    "ubs",
    "credit suisse",
    "julius baer",
    "raiffeisen",
    "zurich insurance",
    "swiss kof",
    "swiss manufacturing pmi",
  ],

  AUD: [
    "reserve bank of australia",
    "rba",
    "aussie",
    "aud",
    "australia inflation",
    "australia cpi",
    "australia gdp",
    "bullock rba",
    "australian bureau of statistics",
    "abs data",
    "employment change australia",
    "rba rate decision",
    "michele bullock",
    "andrew hauser",
    "rba rate cut",
    "rba rate hike",
    "australia trade balance",
    "australia retail sales",
    "asx 200",
    "canberra economic",
    "westpac consumer sentiment",
    "nab business confidence",
    // additions (banks + indicators)
    "nab",
    "westpac",
    "commonwealth bank",
    "cba",
    "anz",
    "macquarie bank",
    "australia bank",
    "australian banking",
    "westpac survey",
    "nab survey",
    "australia building approvals",
    "australia dwelling approvals",
    "australia pmi",
    "australia services pmi",
    "melbourne institute",
    "australia consumer confidence",
    "australia business confidence",
  ],

  NZD: [
    "reserve bank of new zealand",
    "rbnz",
    "kiwi",
    "nzd",
    "new zealand inflation",
    "new zealand cpi",
    "new zealand gdp",
    "orr rbnz",
    "stats nz",
    "official cash rate",
    "christian hawkesby",
    "rbnz rate decision",
    "rbnz rate cut",
    "rbnz rate hike",
    "nz trade balance",
    "nz employment",
    "nz business confidence",
    "wellington economic",
    "nzx 50",
    // additions
    "anz new zealand",
    "asb bank",
    "westpac new zealand",
    "bnz",
    "kiwibank",
    "nz consumer confidence",
    "anz business outlook",
    "nz rei",
    "new zealand rei",
  ],

  CAD: [
    "bank of canada",
    "boc",
    "loonie",
    "cad",
    "canada inflation",
    "canada cpi",
    "canada gdp",
    "macklem",
    "statistics canada",
    "overnight rate canada",
    "canadian dollar",
    "tiff macklem",
    "carolyn rogers",
    "boc rate decision",
    "boc rate cut",
    "boc rate hike",
    "canada trade balance",
    "canada employment",
    "canada jobs report",
    "tsx composite",
    "ottawa economic",
    // additions
    "royal bank of canada",
    "rbc",
    "toronto dominion",
    "td bank",
    "scotiabank",
    "bmo",
    "cibc",
    "national bank of canada",
    "canada housing starts",
    "teranet house price",
    "canada manufacturing pmi",
    "ivey pmi",
  ],

  CNY: [
    "people's bank of china",
    "pboc",
    "yuan",
    "renminbi",
    "cny",
    "rmb",
    "china inflation",
    "china cpi",
    "china gdp",
    "china trade balance",
    "national bureau of statistics china",
    "china property crisis",
    "pan gongsheng",
    "pboc rate decision",
    "loan prime rate",
    "china exports",
    "china imports",
    "china retail sales",
    "china industrial production",
    "shanghai composite",
    "hang seng",
    "beijing economic",
    "yuan devaluation",
    "china stimulus",
    "china tariffs",
    // additions
    "icbc",
    "bank of china",
    "ccb",
    "agricultural bank of china",
    "evergrande",
    "country garden",
    "caixin pmi",
    "china pmi",
    "li keqiang index",
  ],

  MXN: [
    "banco de mexico",
    "banxico",
    "peso mexicano",
    "mexican peso",
    "mxn",
    "mexico inflation",
    "mexico gdp",
    "mexico cpi",
    "rodriguez banxico",
    "victoria rodriguez valdez",
    "banxico rate decision",
    "banxico rate cut",
    "mexico trade balance",
    "mexico remittances",
    "mexico city economic",
    // additions
    "bbva mexico",
    "banorte",
    "banamex",
    "citibanamex",
    "grupo financiero",
  ],

  SEK: [
    "riksbank",
    "swedish krona",
    "sek",
    "sweden inflation",
    "sweden gdp",
    "sweden cpi",
    "thedeen riksbank",
    "erik thedeen",
    "riksbank rate decision",
    "riksbank rate cut",
    "stockholm economic",
    "sweden pmi",
    // additions
    "swedbank",
    "seb",
    "handelsbanken",
    "nordea",
    "swedish business confidence",
  ],

  NOK: [
    "norges bank",
    "norwegian krone",
    "nok",
    "norway inflation",
    "norway gdp",
    "norway cpi",
    "bache norges bank",
    "ida wolden bache",
    "norges bank rate decision",
    "norway oil fund",
    "oslo economic",
    "norway sovereign wealth fund",
    // additions
    "dnb bank",
    "equinor",
    "norwegian oil",
    "brent crude",
    "statnett",
  ],

  SGD: [
    "monetary authority of singapore",
    "mas singapore",
    "singapore dollar",
    "sgd",
    "singapore inflation",
    "singapore gdp",
    "singapore cpi",
    "chia der jiun",
    "mas policy statement",
    "singapore trade balance",
    "singapore non-oil exports",
    "straits times index",
    // additions
    "dbs bank",
    "ocbc",
    "uob",
    "singapore manufacturing pmi",
  ],

  TRY: [
    "central bank of turkey",
    "tcmb",
    "turkish lira",
    "turkey inflation",
    "turkey cpi",
    "turkey gdp",
    "karahan tcmb",
    "fatih karahan",
    "cbrt rate decision",
    "cbrt rate cut",
    "cbrt rate hike",
    "istanbul economic",
    "borsa istanbul",
    "turkey current account",
    // additions
    "akbank",
    "garanti bbva",
    "is bank",
    "yapi kredi",
    "turkish banks",
  ],

  INR: [
    "reserve bank of india",
    "rbi",
    "indian rupee",
    "inr",
    "india inflation",
    "india cpi",
    "india gdp",
    "malhotra rbi",
    "monetary policy committee india",
    "sanjay malhotra",
    "rbi rate decision",
    "rbi rate cut",
    "rbi rate hike",
    "india trade balance",
    "india industrial production",
    "sensex",
    "nifty 50",
    "mumbai economic",
    "india wpi",
    // additions
    "state bank of india",
    "sbi",
    "hdfc bank",
    "icici bank",
    "axis bank",
    "india gst collection",
    "india pmi",
    "bombay stock exchange",
  ],

  ZAR: [
    "south african reserve bank",
    "sarb",
    "south african rand",
    "zar",
    "south africa inflation",
    "south africa cpi",
    "south africa gdp",
    "kganyago",
    "lesetja kganyago",
    "sarb rate decision",
    "sarb rate cut",
    "south africa trade balance",
    "jse all share",
    "pretoria economic",
    "south africa load shedding",
    // additions
    "standard bank",
    "absa",
    "first national bank",
    "nedbank",
    "investec",
    "south africa mining",
    "eskom",
  ],

  BRL: [
    "banco central do brasil",
    "bcb brazil",
    "brazilian real",
    "brl",
    "brazil inflation",
    "brazil cpi",
    "brazil gdp",
    "selic rate",
    "galipolo bcb",
    "gabriel galipolo",
    "bcb rate decision",
    "bcb rate cut",
    "bcb rate hike",
    "brazil trade balance",
    "bovespa",
    "brasilia economic",
    "brazil ipca",
    // additions
    "itau",
    "bradesco",
    "santander brazil",
    "banco do brasil",
  ],

  HKD: [
    "hong kong monetary authority",
    "hkma",
    "hong kong dollar",
    "hkd",
    "hong kong peg",
    "hong kong inflation",
    "hong kong gdp",
    "eddie yue",
    "hkma rate decision",
    "hang seng index",
    "hong kong linked exchange rate",
    "hong kong trade balance",
    // additions
    "hsbc hong kong",
    "hang seng bank",
    "bank of china hong kong",
  ],
};

// ---------------------------------------------------------------------------
// 4. COMPOSITE SCORE WEIGHTS — tune these after backtesting, don't guess-and-forget
// ---------------------------------------------------------------------------
const SCORE_WEIGHTS = {
  technical: 0.5, // price-action based CSI (OANDA candles)
  fundamental: 0.3, // policy rate + long yield z-scores (FRED)
  sentiment: 0.2, // LLM-scored news sentiment (Groq)
};

// ---------------------------------------------------------------------------
// 5. MISC CONFIG
// ---------------------------------------------------------------------------
const OANDA = {
  apiKey: process.env.OANDA_API_KEY,
  accountId: process.env.OANDA_ACCOUNT_ID,
  baseUrl: "https://api-fxtrade.oanda.com",
  // timeframes used for the technical layer — blend short + long for stability
  granularities: ["H4", "D"],
  candleCount: 500,
};

const FRED = {
  apiKey: process.env.FRED_API_KEY,
  baseUrl: "https://api.stlouisfed.org/fred/series/observations",
};

const GROQ = {
  apiKey: process.env.GROQ_API_KEY,
  model: process.env.GROQ_MODEL || "llama-3.1-8b-instant",
};

const MONGO_URI =
  process.env.MONGO_URL || "mongodb://localhost:27017/forex_strength";

module.exports = {
  FOREX_PAIRS,
  STRENGTH_PAIRS,
  CURRENCIES,
  FRED_POLICY_RATE_SERIES,
  FRED_LONG_YIELD_SERIES,
  NEWS_FEEDS,
  CURRENCY_KEYWORDS,
  SCORE_WEIGHTS,
  OANDA,
  FRED,
  GROQ,
  MONGO_URI,
};
